<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="7.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MCPanel.csproj" />
    <Reference Include="SharpSvn">
      <HintPath>..\Vendor\SharpSvn\SharpSvn.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <None Include="..\Vendor\SharpSvn\SharpPlink-x64.svnExe" Link="SharpPlink-x64.svnExe" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
